version: 2

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install "poetry==1.8.4"
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev

# build:
#   os: ubuntu-24.04
#   tools:
#     python: '3.11'
#   jobs:
#     post_install:
#       - pip install "poetry==1.8.4"
#       - poetry config virtualenvs.create false
#       - poetry install --with dev

mkdocs:
  configuration: mkdocs.yml
  # Temporarily allow warnings
  fail_on_warning: false

# # Optionally declare the Python requirements required to build your docs
# python:
#    install:
#    - requirements: docs/requirements.txt
