name: Maestro Workflow Conductor

icon: https://raw.githubusercontent.com/LLNL/maestrowf/develop/assets/logo_icon.png

headline: Orchestrate your HPC workflows with ease

description: Maestro is an open-source HPC software tool that defines a YAML-based study specification for defining multistep workflows and automates execution of software flows on HPC resources. The core design tenants of Maestro focus on encouraging clear workflow communication and documentation, while making consistent execution easier to allow users to focus on science. Maestro's study specification helps users think about complex workflows in a step-wise, intent-oriented, manner that encourages modularity and tool reuse. These principles are becoming increasingly important as computational science is continuously more present in scientific fields and has started to require a similar rigor to physical experiment. Maestro is currently in use for multiple projects at Lawrence Livermore National Laboratory and has been used to run existing codes including MFEM, and other simulation codes. It has also been used in other areas including in the training of machine-learned models and more.

documentation:
  general: https://maestrowf.readthedocs.io/en/latest/
  installation: https://maestrowf.readthedocs.io/en/latest/installing.html
  tutorial: https://github.com/LLNL/maestrowf/tree/develop/samples
