site_name: Maestro Design Docs
use_directory_urls: false
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ['.']
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_div_format #mermaid2.fence_mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format #mermaid.fence_mermaid 
        # - name: mermaid_center
        #   class: mermaid
        #   format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - search
    - mkdocstrings
        # handler: python
    - gen-files:
        scripts:
          - docs/gen_api_docs.py
    - literate-nav:
        nav_file: SUMMARY.md
    # - mermaid2:
    #     arguments:
    #       securityLevel: 'loose'
    #       theme: 'default'
            # darkMode: True
          # theme: |
          #   ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

extra_css:
  - custom.css
  
theme:
  name: material
  logo: assets/logo2.png
  features:
    - header.autohide
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.expand
    - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: blue
  custom_dir: docs/overrides
nav:
    - 'index2.md'  
    - Home: 'index.md'
    - Philosophy:
        - Background: "Philosophy/index.md"
        - How are Workflows Represented?: "Philosophy/representation.md"
        - Principles: "Philosophy/principles.md"
    - Maestro:
        - Overview: 'Maestro/index.md'
        - Installation: 'Maestro/install.md'
        - Tutorials: 'Maestro/tutorials.md'
        - Specification:
            - Specification 1.0: 'Maestro/specification.md'
            - Scheduling Studies: 'Maestro/scheduling.md'
        - Specifying Study Parameters: 'Maestro/parameter_specification.md'
        - Reference Guide:
            - Design Reference: 'Maestro/reference.md'
            - API Reference: Maestro/api_reference/

            # - API Reference: 'reference/'
              
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LLNL/maestrowf
      name: Maestro on GitHub
copyright: Copyright &copy; 2021 | Francesco Di Natale
